module.exports = {
	'jsdoc/check-access': 'off',
	'jsdoc/check-alignment': ['error'],
	'jsdoc/check-examples': 'off',
	'jsdoc/check-indentation': 'off',
	'jsdoc/check-param-names': ['error'],
	'jsdoc/check-property-names': 'off',
	'jsdoc/check-syntax': 'off',
	'jsdoc/check-tag-names': ['error'],
	'jsdoc/check-types': 'off',
	'jsdoc/check-values': 'off',
	'jsdoc/empty-tags': 'off',
	'jsdoc/implements-on-classes': 'off',
	'jsdoc/match-description': 'off',
	'jsdoc/newline-after-description': ['error', 'never'],
	'jsdoc/no-types': ['error', { 'contexts': ['any'] }],
	'jsdoc/no-undefined-types': 'off',
	'jsdoc/require-description-complete-sentence': 'off',
	'jsdoc/require-description': ['error'],
	'jsdoc/require-jsdoc': ['error', {
		'checkGetters': true,
		'checkSetters': true,
		'contexts': [
			'ClassDeclaration',
			'FunctionDeclaration',
			'TSEnumDeclaration',
			'TSInterfaceDeclaration',
			'TSMethodSignature',
			'TSPropertySignature',
		],
		'publicOnly': false,
		'require': {
			'ClassDeclaration': true,
			'FunctionDeclaration': true,
			'MethodDefinition': true,
		},
	}],
	'jsdoc/require-param-description': ['error', {
		'contexts': ['FunctionDeclaration', 'MethodDefinition'],
	}],
	'jsdoc/require-param-name': ['error', {
		'contexts': ['FunctionDeclaration', 'MethodDefinition'],
	}],
	'jsdoc/require-param-type': 'off',
	'jsdoc/require-param': ['error', {
		'enableFixer': true,
		'enableRootFixer': true,
		'enableRestElementFixer': true,
		'checkRestProperty': true,
		'autoIncrementBase': 0,
		'unnamedRootBase': ['root'],
		'contexts': ['FunctionDeclaration', 'MethodDefinition'],
		'checkConstructors': true,
		'checkGetters': true,
		'checkSetters': true,
		'checkDestructured': true,
		'checkDestructuredRoots': true,
	}],
	'jsdoc/require-property': 'off',
	'jsdoc/require-property-description': 'off',
	'jsdoc/require-property-name': 'off',
	'jsdoc/require-property-type': 'off',
	'jsdoc/require-returns-check': ['error', {
		'contexts': ['FunctionDeclaration', 'MethodDefinition'],
	}],
	'jsdoc/require-returns-description': ['error', {
		'contexts': ['FunctionDeclaration', 'MethodDefinition'],
	}],
	'jsdoc/require-returns-type': 'off',
	'jsdoc/require-returns': ['error', {
		'checkConstructors': false,
		'checkGetters': true,
		'forceRequireReturn': false,
		'forceReturnsWithAsync': false,
		'contexts': ['FunctionDeclaration', 'MethodDefinition'],
	}],
	'jsdoc/require-throws': 'off',
	'jsdoc/valid-types': 'off',
};
